version: '3.5'

services:
#  mysql:
#    image: mysql:8
#    ports:
#      - "3306:3306"
#    volumes:
#      - var/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: "password"

  redis:
    image: redis

  notifier:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.local
    volumes:
      - ./:/var/www/html
    command: tail -f /dev/null
    #depends_on:
      #- redis
      #- mysql